const COUNTRY_DATA = {
  'Poland':['Polska','🇵🇱','Warszawa',37.6,.81,72], 'Germany':['Niemcy','🇩🇪','Berlin',84.4,4.46,86], 'France':['Francja','🇫🇷','Paryż',68.2,3.03,82], 'United Kingdom':['Wielka Brytania','🇬🇧','Londyn',68.3,3.34,83],
  'United States of America':['Stany Zjednoczone','🇺🇸','Waszyngton',334.9,27.36,98], 'United States':['Stany Zjednoczone','🇺🇸','Waszyngton',334.9,27.36,98], 'Canada':['Kanada','🇨🇦','Ottawa',39.1,2.14,81], 'Brazil':['Brazylia','🇧🇷','Brasília',203.1,2.17,76],
  'China':['Chiny','🇨🇳','Pekin',1410,17.79,96], 'India':['Indie','🇮🇳','Nowe Delhi',1428,3.57,89], 'Japan':['Japonia','🇯🇵','Tokio',124.5,4.21,85], 'Russian Federation':['Rosja','🇷🇺','Moskwa',143.8,2.02,91], 'Russia':['Rosja','🇷🇺','Moskwa',143.8,2.02,91],
  'Australia':['Australia','🇦🇺','Canberra',26.6,1.72,79], 'Mexico':['Meksyk','🇲🇽','Meksyk',128.5,1.79,70], 'Ukraine':['Ukraina','🇺🇦','Kijów',36.7,.18,74], 'Italy':['Włochy','🇮🇹','Rzym',58.9,2.25,78], 'Spain':['Hiszpania','🇪🇸','Madryt',48.1,1.58,76],
  'Turkey':['Turcja','🇹🇷','Ankara',85.3,1.11,80], 'Türkiye':['Turcja','🇹🇷','Ankara',85.3,1.11,80], 'South Korea':['Korea Południowa','🇰🇷','Seul',51.7,1.71,84], 'Norway':['Norwegia','🇳🇴','Oslo',5.5,.49,77], 'Sweden':['Szwecja','🇸🇪','Sztokholm',10.6,.59,78],
  'Argentina':['Argentyna','🇦🇷','Buenos Aires',46.2,.64,69], 'South Africa':['Republika Południowej Afryki','🇿🇦','Pretoria',60.4,.38,68], 'Egypt':['Egipt','🇪🇬','Kair',112.7,.40,72], 'Nigeria':['Nigeria','🇳🇬','Abudża',223.8,.36,66], 'Saudi Arabia':['Arabia Saudyjska','🇸🇦','Rijad',36.9,1.07,80]
};
const POLISH_PROVINCES=['Mazowieckie','Śląskie','Wielkopolskie','Małopolskie','Dolnośląskie','Łódzkie','Pomorskie','Lubelskie','Podkarpackie','Kujawsko-Pomorskie','Zachodniopomorskie','Warmińsko-Mazurskie','Świętokrzyskie','Podlaskie','Lubuskie','Opolskie'];
const GENERIC_REGIONS=['Region stołeczny','Region północny','Region północno-wschodni','Region wschodni','Region centralny','Region zachodni','Region południowy','Region nadmorski'];
const BUILDINGS=[['🏭','Fabryka cywilna',6.2,45,'+0.35 mld/mies.'],['⚙','Fabryka wojskowa',8.4,60,'sprzęt dla armii'],['⚡','Elektrownia',4.8,35,'+12 energii'],['🏙','Rozbudowa miasta',5.5,50,'+6 rozwoju'],['🛣','Infrastruktura',3.2,30,'+15% produkcji'],['🔬','Centrum badawcze',9.1,70,'+4 nauki/dzień']];
const NAMES = typeof Intl.DisplayNames === 'function' ? new Intl.DisplayNames(['pl'],{type:'region'}) : null;
let game={country:'Poland',money:48.2,population:37.6,manpower:642,stability:82,date:new Date('2025-01-01T08:00:00Z'),speed:1,paused:false,province:'Mazowieckie',armies:[{name:'1. Armia Lądowa',type:'Piechota zmotoryzowana',size:12400,readiness:92,province:'Mazowieckie'}],builds:[],relations:{},wars:[],buildings:0,provinceBuildings:{}};
let map, borders, worldBorders, adminBorders, currentFeature, currentCountry, mapMode='political', viewLevel='world', moveMode=false, armyMarkers=[], countryList=Object.entries(COUNTRY_DATA).filter(([key],n,list)=>list.findIndex(([,value])=>value[0]===COUNTRY_DATA[key][0])===n).map(([key,data])=>({key,data})).sort((a,b)=>a.data[0].localeCompare(b.data[0],'pl'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function fallbackInfo(name,iso=''){const code=(iso||'UN').toUpperCase();let polish=NAMES&&code.length===2?NAMES.of(code):name;return [polish||name,'🌐',name,Math.round(5+Math.random()*80),.15,55]}
function infoFor(feature){const p=feature.properties||{};const english=p.name||p.NAME||p['name:en']||'Państwo';const iso=p['iso-a2']||p.ISO_A2||p.iso_a2||'';return {key:english,iso,data:COUNTRY_DATA[english]||fallbackInfo(english,iso)}}
function color(feature){const i=infoFor(feature), own=i.key===game.country;if(own)return '#d98a45';if(mapMode==='economy')return i.data[4]>3?'#3d9d77':i.data[4]>1?'#568970':'#536b70';if(mapMode==='military')return i.data[5]>85?'#a95049':i.data[5]>70?'#a77a4d':'#526f7d';if(mapMode==='relations'){const r=game.relations[i.key]??0;return r>20?'#3e8f78':r<0?'#a65049':'#627785'}return ['#496f7c','#587d85','#627589','#466f72','#706d82'][Math.abs(hash(i.key))%5]}
function hash(s){return [...s].reduce((a,c)=>((a<<5)-a)+c.charCodeAt(0),0)}
function mapStyle(feature){return {fillColor:color(feature),weight:feature===currentFeature?3:1.1,color:feature===currentFeature?'#ffe08a':'#07131d',fillOpacity:.94}}
function adminStyle(feature){const name=feature.properties.name||feature.properties.NAME||'';const selected=name===game.province;let fill=['#31566b','#395f72','#426679','#355b70'][Math.abs(hash(name))%4];if(mapMode==='economy'){const built=game.provinceBuildings[name]||0;fill=built>=3?'#2f956e':built?'#4b806c':'#536a70'}if(mapMode==='military')fill=game.armies.some(a=>a.province===name)?'#b16f40':'#455f6d';if(mapMode==='relations')fill=currentCountry?.key===game.country?'#3d816e':'#7d5556';return {fillColor:selected?'#d98a45':fill,weight:selected?3:1.3,color:selected?'#ffe08a':'#091824',fillOpacity:.96}}
function setupMap(){
  if(!window.L){$('#mapLoading b').textContent='Nie udało się wczytać silnika mapy';return}
  map=L.map('map',{center:[25,12],zoom:2,minZoom:2,maxZoom:9,zoomControl:false,worldCopyJump:true,attributionControl:false,zoomSnap:.25});L.control.zoom({position:'bottomleft'}).addTo(map);
  fetch('https://code.highcharts.com/mapdata/custom/world-highres.geo.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{
    countryList=data.features.map(infoFor).sort((a,b)=>a.data[0].localeCompare(b.data[0],'pl'));renderCountryPicker();
    worldBorders=L.geoJSON(data,{style:mapStyle,onEachFeature:(feature,layer)=>{const i=infoFor(feature);layer.bindTooltip(`${i.data[1]} ${i.data[0]}`,{sticky:true,className:'country-tip'});layer.on({click:()=>selectFeature(feature,layer),mouseover:()=>layer.setStyle({weight:2.4,color:'#f1cb72'}),mouseout:()=>worldBorders.resetStyle(layer)})}}).addTo(map);borders=worldBorders;
    const poland=data.features.find(f=>infoFor(f).key==='Poland');if(poland)currentFeature=poland;worldBorders.setStyle(mapStyle);$('#mapLoading').classList.add('hidden');
  }).catch(()=>{$('#mapLoading b').textContent='Nie udało się pobrać granic politycznych';$('#mapLoading small').textContent='Uruchom grę z połączeniem internetowym'});
}
function selectFeature(feature,layer){currentFeature=feature;worldBorders.setStyle(mapStyle);layer.setStyle({weight:3,color:'#ffe08a'});const i=infoFor(feature);renderCountry(i);loadAdminMap(i,layer.getBounds())}
async function loadAdminMap(i,bounds){
  const iso=(i.iso||'').toLowerCase();if(!iso||iso.length!==2){map.fitBounds(bounds,{padding:[35,35]});return toast('Brak mapy regionów dla tego terytorium')}
  $('#mapLoading').classList.remove('hidden');$('#mapLoading b').textContent=`Wczytywanie regionów: ${i.data[0]}…`;
  try{const response=await fetch(`https://code.highcharts.com/mapdata/countries/${iso}/${iso}-all.geo.json`);if(!response.ok)throw Error(response.status);const data=await response.json();
    if(adminBorders)adminBorders.remove();worldBorders.remove();viewLevel='admin';currentCountry=i;$('#mapRegion').textContent=i.data[0].toUpperCase();$('.map-breadcrumb').classList.add('visible');$('#mapHelp').textContent='Kliknij region, aby go wybrać, budować lub wydać rozkaz ruchu';
    adminBorders=L.geoJSON(data,{style:adminStyle,onEachFeature:(feature,region)=>{const name=feature.properties.name||feature.properties.NAME||'Region';region.bindTooltip(name,{sticky:true,className:'country-tip'});region.on({click:()=>selectProvince(feature,region),mouseover:()=>region.setStyle({weight:2.6,color:'#f2cc72'}),mouseout:()=>adminBorders.resetStyle(region)})}}).addTo(map);borders=adminBorders;map.fitBounds(adminBorders.getBounds(),{padding:[25,25]});renderAdminList(data.features);renderArmyMarkers();
  }catch{map.fitBounds(bounds,{padding:[35,35]});toast('To terytorium nie ma dostępnego podziału administracyjnego')}
  $('#mapLoading').classList.add('hidden');
}
function selectProvince(feature,layer){const name=feature.properties.name||feature.properties.NAME||'Region';game.province=name;adminBorders.setStyle(adminStyle);layer.setStyle({weight:3,color:'#ffe08a'});$('#buildProvince').textContent=name;renderAdminList(adminBorders.toGeoJSON().features);if(moveMode&&game.armies.length){game.armies[0].province=name;moveMode=false;$('#map').classList.remove('move-mode');toast(`1. Armia otrzymała rozkaz marszu do: ${name}`);renderArmyMarkers()}else toast(`Wybrano region: ${name}`)}
function renderAdminList(features){const names=features.map(f=>f.properties.name||f.properties.NAME).filter(Boolean);$('#provinceCount').textContent=`${names.length} regionów`;$('#provinceList').innerHTML=names.map((r,n)=>`<button class="province-row ${r===game.province?'selected':''}" data-province="${r}"><span>${n===0?'★':'◆'}</span><div><b>${r}</b><small>${(1.5+(hash(r)%70+70)%70/10).toFixed(1)} mln · ${game.provinceBuildings[r]||0} budynków</small></div><em>›</em></button>`).join('')}
function showWorld(){if(adminBorders)adminBorders.remove();adminBorders=null;worldBorders.addTo(map);borders=worldBorders;viewLevel='world';currentCountry=null;$('.map-breadcrumb').classList.remove('visible');$('#mapHelp').textContent='Kliknij państwo, aby wejść na mapę jego prowincji';map.setView([25,12],2);clearArmyMarkers();worldBorders.setStyle(mapStyle)}
function clearArmyMarkers(){armyMarkers.forEach(m=>m.remove());armyMarkers=[]}
function renderArmyMarkers(){clearArmyMarkers();if(viewLevel!=='admin'||currentCountry?.key!==game.country)return;game.armies.forEach((army,index)=>{let target;adminBorders.eachLayer(l=>{const n=l.feature.properties.name||l.feature.properties.NAME;if(n===army.province)target=l});if(!target)return;const marker=L.marker(target.getBounds().getCenter(),{icon:L.divIcon({className:'army-map-token',html:`<span>⚔</span><b>${Math.round(army.size/100)/10}K</b>`,iconSize:[52,45],iconAnchor:[26,23]})}).addTo(map);marker.bindTooltip(`${army.name}<br>${army.size.toLocaleString('pl')} żołnierzy`);armyMarkers.push(marker)})}
function renderCountry(i){const [name,flag,capital,pop,gdp,power]=i.data;$('#selectedName').textContent=name.toUpperCase();$('#selectedFlag').textContent=flag;$('#selectedCapital').textContent=capital;$('#selPop').textContent=`${pop} mln`;$('#selGdp').textContent=`${gdp} bln $`;$('#selPower').textContent=power;const own=i.key===game.country;const rel=own?100:(game.relations[i.key]??0);$('#relation').textContent=own?'Własne państwo':rel>20?'Przyjazne':rel<0?'Napięte':'Neutralne';$('#relation').className=rel<0?'bad':rel>20||own?'good':'';$('#diploValue').textContent=rel;$('#diploFlag').textContent=flag;$('#declareWar').disabled=own;renderProvinces(own&&i.key==='Poland'?POLISH_PROVINCES:GENERIC_REGIONS)}
function renderProvinces(regions){$('#provinceCount').textContent=`${regions.length} regionów`;$('#provinceList').innerHTML=regions.map((r,n)=>`<button class="province-row ${r===game.province?'selected':''}" data-province="${r}"><span>${n===0?'★':'◆'}</span><div><b>${r}</b><small>${(1.5+(hash(r)%70+70)%70/10).toFixed(1)} mln · rozwój ${45+(Math.abs(hash(r))%40)}</small></div><em>›</em></button>`).join('')}
function renderCountryPicker(){const q=$('#countrySearch').value.toLowerCase();$('#countryGrid').innerHTML=countryList.filter(i=>i.data[0].toLowerCase().includes(q)).map(i=>`<button type="button" class="country-option ${i.key===game.country?'selected':''}" data-key="${i.key}"><span>${i.data[1]}</span><b>${i.data[0]}</b><small>${i.data[2]}</small></button>`).join('')}
function startAs(key){const i=countryList.find(c=>c.key===key)||{key:'Poland',data:COUNTRY_DATA.Poland};game.country=i.key;game.population=i.data[3];game.province=i.key==='Poland'?'Mazowieckie':'Region stołeczny';$('#playerFlag').textContent=i.data[1];$('#playerCountry').textContent=i.data[0];updateUI();renderCountry(i);worldBorders?.setStyle(mapStyle);if(worldBorders){worldBorders.eachLayer(layer=>{if(infoFor(layer.feature).key===i.key)loadAdminMap(i,layer.getBounds())})}toast(`Rozpoczęto grę jako: ${i.data[0]}`)}
function updateUI(){
  $('#money').textContent=game.money.toFixed(2);$('#population').textContent=game.population.toFixed(1);$('#manpower').textContent=Math.floor(game.manpower);$('#stability').textContent=Math.floor(game.stability);
  $('#gameDate').textContent=game.date.toLocaleDateString('pl-PL',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase();$('#gameTime').textContent=game.date.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'});
  $('#incomeRate').textContent=`+${(1.8+game.buildings*.35).toFixed(2)}/mies.`;renderBuildQueue();renderArmies();
}
function gameTick(){if(game.paused)return;game.date=new Date(game.date.getTime()+game.speed*6*3600000);game.money+=(1.8+game.buildings*.35)/120*game.speed;game.manpower+=.12*game.speed;game.builds.forEach(b=>b.left-=game.speed/4);const done=game.builds.filter(b=>b.left<=0);done.forEach(b=>{game.buildings++;game.provinceBuildings[b.province]=(game.provinceBuildings[b.province]||0)+1;toast(`Ukończono: ${b.name} w ${b.province}`)});game.builds=game.builds.filter(b=>b.left>0);updateUI();if(game.date.getUTCHours()===2&&Math.random()<.06)randomEvent()}
function randomEvent(){const events=['Rynki światowe notują wzrost','Rozpoczęto międzynarodowe ćwiczenia wojskowe','Nowa umowa handlowa weszła w życie','Napięcia dyplomatyczne rosną w jednym z regionów'];$('#tickerText').textContent=events[Math.floor(Math.random()*events.length)]}
function renderBuildings(){$('#buildGrid').innerHTML=BUILDINGS.map((b,i)=>`<button class="build-card" data-build="${i}"><span>${b[0]}</span><b>${b[1]}</b><small>${b[4]}</small><em>${b[2]} mld $ · ${b[3]} dni</em></button>`).join('')}
function build(index){const b=BUILDINGS[index];if(game.money<b[2])return toast('Za mało środków w skarbcu');game.money-=b[2];game.builds.push({name:b[1],province:game.province,left:b[3]});updateUI();toast(`Rozpoczęto budowę: ${b[1]}`)}
function renderBuildQueue(){if(!game.builds.length){$('#buildQueue').className='queue empty';$('#buildQueue').textContent='Brak aktywnych inwestycji';return}$('#buildQueue').className='queue';$('#buildQueue').innerHTML=game.builds.map(b=>`<div><b>${b.name}</b><small>${b.province} · ${Math.ceil(b.left)} dni</small><progress value="${Math.max(1,70-b.left)}" max="70"></progress></div>`).join('')}
function renderArmies(){$('#armyList').innerHTML=game.armies.map((a,i)=>`<article class="army"><span>⚔</span><div><b>${a.name}</b><small>${a.type} · gotowość ${a.readiness}%</small><progress value="${a.readiness}" max="100"></progress></div><strong>${a.size.toLocaleString('pl')}</strong><button data-disband="${i}" title="Rozwiąż">×</button></article>`).join('')}
function recruit(){const size=Number($('#armySize').value);const cost=size*.0003;if(game.money<cost||game.manpower<size/1000)return toast('Brak pieniędzy lub rezerw osobowych');game.money-=cost;game.manpower-=size/1000;game.armies.push({name:$('#armyName').value||'Nowa armia',type:$('#armyType').value,size,readiness:55,province:game.province});updateUI();renderArmyMarkers();toast('Nowa armia pojawiła się w wybranym regionie')}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}

$$('.panel-tabs button').forEach(b=>b.onclick=()=>{$$('.panel-tabs button').forEach(x=>x.classList.remove('active'));$$('.tab-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.tab}Page`).classList.add('active')});
$$('[data-mapmode]').forEach(b=>b.onclick=()=>{$$('[data-mapmode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mapMode=b.dataset.mapmode;if(viewLevel==='world')worldBorders?.setStyle(mapStyle);else adminBorders?.setStyle(adminStyle)});
$$('.time-btn[data-speed]').forEach(b=>b.onclick=()=>{game.speed=Number(b.dataset.speed);game.paused=false;$$('.time-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#pause').onclick=()=>{game.paused=!game.paused;$('#pause').classList.toggle('active',game.paused);toast(game.paused?'Gra zatrzymana':'Czas wznowiony')};
$('#provinceList').onclick=e=>{const row=e.target.closest('[data-province]');if(!row)return;game.province=row.dataset.province;$('#buildProvince').textContent=game.province;$$('.province-row').forEach(x=>x.classList.toggle('selected',x===row));if(adminBorders){adminBorders.setStyle(adminStyle);adminBorders.eachLayer(l=>{const name=l.feature.properties.name||l.feature.properties.NAME;if(name===game.province){l.setStyle({weight:3,color:'#ffe08a'});map.fitBounds(l.getBounds(),{padding:[90,90],maxZoom:7})}})}$$('.panel-tabs button')[1].click()};
$('#buildGrid').onclick=e=>{const card=e.target.closest('[data-build]');if(card)build(Number(card.dataset.build))};
$('#recruitOpen').onclick=()=>$('#recruitDialog').showModal();$('#confirmRecruit').onclick=recruit;$('#armySize').oninput=e=>$('#armySizeOut').textContent=`${Number(e.target.value).toLocaleString('pl')} żołnierzy`;
$('#armyList').onclick=e=>{const b=e.target.closest('[data-disband]');if(!b)return;game.armies.splice(Number(b.dataset.disband),1);renderArmies();toast('Armia została rozwiązana')};
$('#trainArmy').onclick=()=>{if(!game.armies.length)return toast('Nie posiadasz armii');game.money-=.3;game.armies.forEach(a=>a.readiness=Math.min(100,a.readiness+5));updateUI();toast('Zakończono ćwiczenia wojskowe')};
$('#moveArmy').onclick=()=>{if(!game.armies.length)return toast('Nie posiadasz armii');if(viewLevel!=='admin'||currentCountry?.key!==game.country)return toast('Najpierw wejdź na mapę własnego państwa');moveMode=true;$('#map').classList.add('move-mode');toast('TRYB RUCHU: kliknij region docelowy na mapie')};
$('#improveRelations').onclick=()=>{game.money-=.5;toast('Dyplomaci rozpoczęli rozmowy');$('#diploValue').textContent=Number($('#diploValue').textContent)+10};$('#tradeDeal').onclick=()=>toast('Wysłano propozycję umowy handlowej');$('#declareWar').onclick=()=>{if(confirm('Czy na pewno chcesz wypowiedzieć wojnę?')){game.stability-=8;toast('Stan wojny! Rozpoczęto mobilizację');updateUI()}};
$('#countrySearch').oninput=renderCountryPicker;$('#countryGrid').onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;$$('.country-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};$('#startGame').onclick=()=>startAs($('#countryGrid .selected')?.dataset.key||'Poland');$('#countryHead').onclick=()=>{$('#startDialog').showModal();renderCountryPicker()};
$('#saveGame').onclick=()=>{localStorage.setItem('worldDominionSave',JSON.stringify(game));toast('Gra zapisana w przeglądarce')};$('#panelClose').onclick=()=>$('#panel').classList.toggle('collapsed');
$('#worldView').onclick=showWorld;
$$('.nav[data-screen]').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.screen==='country'){const i=COUNTRY_DATA[game.country]||fallbackInfo(game.country);$('#reportTitle').textContent=i[0];$('#reportBody').innerHTML=`<div class="report-stats"><div><b>${game.money.toFixed(1)}</b><small>mld $ w skarbcu</small></div><div><b>${game.armies.length}</b><small>armie</small></div><div><b>${game.buildings}</b><small>ukończone inwestycje</small></div></div>`;$('#reportDialog').showModal()}else if(b.dataset.screen!=='map'){const tab={economy:'build',military:'forces',diplomacy:'diplo',research:'build'}[b.dataset.screen];if(tab)document.querySelector(`[data-tab="${tab}"]`).click();toast('Otworzono moduł: '+b.textContent.trim())}});
renderBuildings();renderProvinces(POLISH_PROVINCES);updateUI();setupMap();setInterval(gameTick,500);
window.addEventListener('load',()=>{const saved=localStorage.getItem('worldDominionSave');if(saved&&confirm('Znaleziono zapis gry. Wczytać?')){try{game={...game,...JSON.parse(saved)};game.date=new Date(game.date);startAs(game.country)}catch{toast('Nie udało się wczytać zapisu')}}else setTimeout(()=>$('#startDialog').showModal(),500)});
